language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - pypy
  - pypy3
install:
  - pip install coveralls
script:
  - coverage run --source=pyeto setup.py test
after_success: coveralls